### ISSUE TITLE
Compatibility with Sphinx v4.0.0

### ISSUE THREAD

**Issue by shimwell** [Peque/sphinxcadquery#20]
Hi there

Just ran into a potential issue, sorry in advance if this turns out to be an error elsewhere.

This build passes
https://readthedocs.org/projects/paramak/builds/13714985/

This build fails
https://readthedocs.org/projects/paramak/builds/13718906/

The main difference is the first build uses Sphinx 3.5.4 and the second build uses the recently released Sphinx 4.0.0

So I am wondering if there is a breaking change that impacts this package in the recently Sphinx 4.0.0

**Comment by Peque** [comment]
@Shimwell Thanks for reporting! :blush: 

It is probably a bug. Sphinx 4 came out very recently and it seems they may have changed the API. As a workaround you can pin your Sphinx version to 3.x until this is fixed in sphinxcadquery.

I don't have time to look into it right now, but pull-requests fixing this issue are more than welcome. :wink:

**Comment by shimwell** [comment]
Thanks for the speedy reply and thanks for making the package. I did a bit of detective work and had a go at a fix but I am not sure of the best way to test this package.

**Comment by Peque** [comment]
@Shimwell I think testing should be as easy as:

```
pip uninstall sphinxcadquery
pip install -e /your/path/to/sphinxcadquery
```

Where `/your/path/to/sphinxcadquery` is where you cloned this repo to make the changes and open the PR.

**Comment by Peque** [comment]
Closed by https://github.com/Peque/sphinxcadquery/pull/25.
